version: "3.9"
services:
  mysql:
    image: mysql:8.3
    container_name: mysql_bench
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=bench_db
      - MYSQL_USER=bench
      - MYSQL_PASSWORD=benchpass
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
